import { postgisPoint, postgisLineString } from "./custom-types.js";
import { pgTable, integer, doublePrecision, bigint, varchar, index } from "drizzle-orm/pg-core";

export const nodes = pgTable("nodes", {
  id: integer("node_id").primaryKey(),
  geom: postgisPoint("geom").notNull(),
  elevation: doublePrecision("elevation"),
});

export const edges = pgTable(
  "edges",
  {
    id: integer("id").primaryKey(),
    osmId: bigint("osm_id", { mode: "number" }).notNull(),

    source: integer("source").notNull(), // Source node ID
    target: integer("target").notNull(), // Target node ID

    // Cost fields generated by osm2po (usually travel time or distance)
    cost: doublePrecision("cost").notNull(),
    reverseCost: doublePrecision("reverse_cost").notNull(),

    // Metadata
    km: doublePrecision("km").notNull(),
    kmh: integer("kmh").notNull(), // Speed limit
    clazz: integer("clazz").notNull(),
    flags: integer("flags").notNull(),
    streetName: varchar("osm_name", { length: 255 }),

    geom: postgisLineString("geom_way").notNull(),
  },
  (table) => ({
    // 2. Defined the GiST spatial index on the geom column
    edgesGeomIdx: index("edges_geom_idx").using("gist", table.geom),
  }),
);

export type Node = typeof nodes.$inferSelect;
export type Edge = typeof edges.$inferSelect;

// Types for inserting data: marks columns like autoincrement, etc. as optional
export type NewNode = typeof nodes.$inferInsert;
export type NewEdge = typeof edges.$inferInsert;
