import { postgisPoint, postgisLineString } from "./custom-types.js";
import { pgTable, integer, doublePrecision, bigint, varchar } from "drizzle-orm/pg-core";

export const consolidatedNodes = pgTable("consolidated_nodes_final", {
  nodeId: integer("node_id").primaryKey(),
  geom: postgisPoint("geom").notNull(),
  elevation: doublePrecision("elevation"),
});

export const networkWays = pgTable("test_net_2po_4pgr", {
  id: integer("id").primaryKey(),
  osmId: bigint("osm_id", { mode: "number" }).notNull(),

  source: integer("source").notNull(), // Source node ID
  target: integer("target").notNull(), // Target node ID

  // Cost fields generated by osm2po (usually travel time or distance)
  cost: doublePrecision("cost").notNull(),
  reverseCost: doublePrecision("reverse_cost").notNull(),

  // Metadata
  km: doublePrecision("km").notNull(),
  kmh: integer("kmh").notNull(), // Speed limit
  clazz: integer("clazz").notNull(),
  flags: integer("flags").notNull(),
  osmName: varchar("osm_name", { length: 255 }),

  geomWay: postgisLineString("geom_way").notNull(),
});
